global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
        - "api.ivanmalks.online"

  - job_name: 'telegraf'
    scrape_interval: 10s # Match Telegraf's interval or scrape more/less often
    static_configs:
      - targets:
        - "telegraf.ivanmalks.online"