global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'external_app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['62.233.43.154:8080']